source:
  fighter: source/fighter
destination:
  fighter: destination/fighter
filetypes:
  - pcs
  - pac

fighter:
  Peach:
    00: RESERVED
    01: Peach/Rosalina
    02:
      - Peach/Rosalina.pcs
      - Peach/Rosalina.pac
