source:
  fighter: source/fighter
destination:
  fighter: destination/fighter
filetypes:
  - pcs
  - pac
fighter:
  Peach:
    00: Peach/Rosalina
    01: Peach/Rosalina.pac
    02: Peach/Rosalina.pcs
    03: RESERVED
